"""Generates `mdk/script/script_opcodes.gd` (operand layouts for the GDScript decoder) and
`docs/script_opcodes.md` (the opcode reference) from `script_opcodes.json`, classifying "complex"
operands like `complex_operand()` in mdk_script_dis.py.

Usage: python gen_script_table.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "mdk", "script", "script_opcodes.gd")
DOC = os.path.join(HERE, "..", "..", "docs", "script_opcodes.md")
DOC_HEADER = """# Script opcodes

Generated from [`tools/python/script_opcodes.json`](../tools/python/script_opcodes.json) by
[`gen_script_table.py`](../tools/python/gen_script_table.py). *Italic* operands have layouts that
depend on other operands (see `complex_operand()` in
[`tools/python/mdk_script_dis.py`](../tools/python/mdk_script_dis.py) and the notes in
[`scripts/`](scripts/)). See [scripts.md](scripts.md) for the interpreter.

| Op | Mnemonic | Operands | Flow | Summary |
| ---: | --- | --- | --- | --- |
"""

# Complex operands handled per opcode in complex_operand(), checked before the generic kinds.
SPECIAL_FIRST = {(4, "command_args"), (4, "selector_args"), (2, "origin"), (164, None), (42, "part"),
                 (249, "sound"), (250, "type_name"), (250, "box"), (174, "b"), (175, "b"), (129, None),
                 (132, None), (89, None)}
# Complex operands handled per opcode after the generic kinds.
SPECIAL_LAST = {61, 83, 159, 189, 193, 245, 248, 172, 178, 173, 180, 181, 203, 224, 228, 242, 158}


def classify(opcode, operand):
    name = operand.get("name")
    if (opcode, name) in SPECIAL_FIRST or (opcode, None) in SPECIAL_FIRST:
        return "op%d_%s" % (opcode, name)
    layout = operand.get("layout", "")
    kind = operand.get("kind")
    if kind in ("action", "cond_action") or layout.startswith(("branch action", "u8 act;", "u8 kind; kind 0xFE")):
        return "action"
    if kind == "value" or layout.startswith(("value:", "u8 src; if src==3", "u8 kind; if kind==3")):
        return "value"
    if kind == "cond" or layout.startswith("u8 op; f32"):
        return "cond"
    if opcode in SPECIAL_LAST:
        return "op%d_%s" % (opcode, name)
    raise KeyError("unclassified complex operand %d %s: %s" % (opcode, name, layout[:60]))


def operand_code(opcode, operand):
    t = operand["type"]
    if t == "complex":
        return classify(opcode, operand)
    if t == "off32":
        data = operand.get("role") == "data" or (opcode, operand["name"]) in {(2, "path"), (28, "path"), (3, "anim"), (59, "anim")}
        return "data32" if data else "code32"
    if t == "repeat":
        items = ",".join("code32" if i["type"] == "off32" else i["type"] for i in operand["items"])
        return "repeat:" + items
    return t


def operand_doc(operand):
    t = operand["type"]
    name = operand.get("name")
    if t == "complex":
        return "%s: *%s*" % (name, operand.get("kind", "complex"))
    if t == "repeat":
        items = ", ".join(operand_doc(i) for i in operand["items"])
        return "repeat(%s × [%s])" % (operand.get("count", "u8"), items)
    return "%s %s" % (t, name) if name else t


def write_doc(ops):
    rows = []
    for o in ops:
        operands = ", ".join(operand_doc(a) for a in o["operands"]) or "—"
        summary = o.get("summary", "").replace("|", "\\|").replace("\n", " ")
        rows.append("| %d | `%s` | %s | %s | %s |" % (o["opcode"], o["mnemonic"], operands, o.get("flow", ""), summary))
    with open(DOC, "w", encoding="utf-8", newline="\n") as f:
        f.write(DOC_HEADER + "\n".join(rows) + "\n")
    print("wrote", DOC)


def main():
    ops = json.load(open(os.path.join(HERE, "script_opcodes.json"), encoding="utf-8"))
    lines = [
        "# Generated by tools/python/gen_script_table.py from tools/python/script_opcodes.json. Don't edit.",
        "## Operand layouts of the script opcodes (see `MDKScriptDecoder`).",
        "class_name MDKScriptOpcodes",
        "extends RefCounted",
        "",
        "## Opcode to its mnemonic.",
        "const MNEMONICS := {",
    ]
    for o in ops:
        lines.append('\t%d: "%s",' % (o["opcode"], o["mnemonic"]))
    lines += ["}", "", "## Opcode to its operand codes: plain types (`u8`, `f32`, `pstr`, …), `code32`/`data32`",
              "## offsets, `repeat:<items>`, `action`, `value`, `cond`, or `opN_name` for special layouts.",
              "const OPERANDS := {"]
    for o in ops:
        if o["opcode"] == 255:
            continue
        codes = ", ".join('"%s"' % operand_code(o["opcode"], a) for a in o["operands"])
        lines.append("\t%d: [%s]," % (o["opcode"], codes))
    lines += ["}", "", "## Opcodes that never continue with the next instruction.",
              "const NO_FALLTHROUGH := [9, 12, 94, 182, 110, 184, 253]", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", OUT)
    write_doc(ops)


if __name__ == "__main__":
    main()
